### ISSUE TITLE
Determine modularisation of server framework configuration

### ISSUE THREAD

**Issue by ml019** [hamlet-io/cloudinit-aws#3]
Servers should be provided with a (possibly versioned) "role", from which the remainder of their configuration will be determined.

Suggest using a role/profile/module approach like puppet - see https://docs.puppet.com/pe/2017.1/r_n_p_intro.html

**Comment by roleyfoley** [comment]
Requirement for managing puppet in #1 which is now no longer required. This can also be achieved via boostraps
