### ISSUE TITLE
Configure jenkins server via server automation framework

### ISSUE THREAD

**Issue by ml019** [hamlet-io/cloudinit-aws#6]
Add an "automation" role that fully configures an automation server
Packages to include

- httpd
- tomcat
- jenkins
- docker
- git
- jq
- dos2unix
- node
- npm
- yarn
- let's encrypt

See https://redmine.gosource.com.au/projects/eticket/wiki/ALM_Setup for sample installation instructions

**Comment by roleyfoley** [comment]
Now part of the hamletio/hamlet and hamletio/jenkins docker images
